# Site settings
title: Erik Runyon
subtitle: WeedyGarden
author: Erik Runyon
baseurl: ""
url: "http://erikrunyon.com"
email: erunyon@gmail.com
description: Home of Erik Runyon. Techinical Director for Marketing Communications at the University of Notre Dame.
simple_search: http://google.com/search
twitter_username: erunyon
github_username:  erunyon

# Build settings
markdown: rdiscount
permalink: /:year/:month/:title/
paginate: 10
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles
excerpt_separator: <!-- more -->
exclude: ['README.md', 'Gemfile.lock', 'Gemfile']

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: http://erikrunyon.com/atom.xml

# SASS
sass:
  sass_dir: css
  style: :compressed # expanded, compact, compressed

# Disqus Comments
disqus_short_name: weedygarden
disqus_show_comment_count: true

# Gems
gems:
  - jekyll-sitemap
  - octopress-autoprefixer