# Site settings
title: Erik Runyon
subtitle: WeedyGarden
author: Erik Runyon
baseurl: ""
port: 3333
url: "https://erikrunyon.com"
email: erunyon@gmail.com
description: Home of Erik Runyon. Technical Director for Marketing Communications at the University of Notre Dame.
simple_search: https://google.com/search
twitter_username: erunyon
github_username:  erunyon

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
permalink: /:year/:month/:title/
paginate: 10
excerpt_link: "continue reading"  # "Continue reading" link text at the bottom of excerpted articles
excerpt_separator: <!-- more -->
include: ['.htaccess', '_redirects']
exclude: [node_modules, 'README.md', 'Gemfile.lock', 'Gemfile']

# RSS / Email (optional) subscription links (change if using something like Feedburner)
feed_rss: https://erikrunyon.com/feed.xml
snippets_rss: https://erikrunyon.com/snippets.xml

# SASS
sass:
  sass_dir: _includes/css
  style: :compressed # expanded, compact, compressed

# Disqus Comments
disqus_short_name: weedygarden
disqus_show_comment_count: true

# Gems
plugins:
  - jekyll-sitemap
  - octopress-autoprefixer
  - jekyll-paginate
  #- jekyll-archives

jekyll-archives:
  enabled: categories
  layout: 'archive'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'
